name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19

      - run: npm ci --ignore-scripts
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
