name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
      permissions:
        contents: write
        issues: write
        pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.17.1
      - run: npm ci --ignore-scripts
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
i

